set define off;
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'고구마 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'고구마 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'그릭 요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'그린티 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'녹차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'녹차 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'녹차 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 요거트스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 쉐이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'딸기 체리 그릭요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'라벤더 허브티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'레몬 복숭아 아이스티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'레몬 쉐이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'레몬 아이스티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'레몬 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'레몬 체리 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'레몬티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'로얄 밀크티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'말차 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'망고 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'망고 레몬 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'망고 바나나 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'망고 스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'망고 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'모카 프라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'민트 초코 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'민트 초코 버블티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'민트 초코 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'민트 초코 그릭요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'밀크 쉐이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'밀크티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'바나나 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'바닐라 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'백향과 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'버블 밀크티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'복숭아 아이스티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'복숭아 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루 레몬 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루베리 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루베리 요거트스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루베리 스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루베리 아보카도 그릭요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루베리 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'블루베리 요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'비건 그릭요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'생강차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'아쌈 허니 밀크티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'아이스티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'얼그레이',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'오곡 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'유자 요거트스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'유자 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'유자차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'잉글리쉬 브렉퍼스트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'자두 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'자몽 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'자몽 유자차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'자몽차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'제주 말차 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'청귤 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'청귤차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'청포도 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'체리 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'초코 쉐이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'초코 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'초코 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'초코 버블티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'카라멜 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'캐모마일',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'쿠키 앤 크림 프라페',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'쿠키 앤 쉐이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'키위 스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'키위 요거트스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'키위 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'타로 버블티',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'토피넛 라떼',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'패션후르츠 에이드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'페퍼민트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'플레인 요거트스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'플레인 요거트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'핫초코',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'허니 유자차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'홍시 스무디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'홍차',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_bmenu_id_seq.nextval,'흑임자 라떼',default);

commit;
