set define off;
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'갈릭 올리오',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'구운 쉬림프 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'그래놀라',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'그릭 하프 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'꽃 맛살 범벅 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'누텔라 아이스크림 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'누텔라 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'뉴 몬테크리스토 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'뉴욕 버거',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'뉴 인기가요 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'단팥 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'단호박 리코타 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'단호박 무스 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'닭가슴살 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'디럭스 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'딸쵸 범벅 페스츄리',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'로제 파스타 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'리얼후르츠 브레드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'리코타치즈 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'말렌카 케이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'메이플 허니브레드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'메이플 피칸',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'몬스터 아이스크림 페스츄리',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'뱅 오 쇼콜라',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'베이직 콥샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'베이컨 치즈 토스트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'브레디드 쉬림프 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'브렉퍼스트 잉글리쉬 머핀',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'블루베리 마카롱',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'블루베리 베이글',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'블루베리 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'블루베리 쿠키 치즈케이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'빠네 크림 떡볶이',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'빠네 크림 파스타',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'빠네 토마토 떡볶이',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'사과 가득 핸디 젤리',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'새코롬 돌코롬 한라봉 케이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'세븐 레이어 가나 슈 케이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'수제 리코타치즈 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'슈파이',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'스위트 포테이토 피자',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'스트로베리 마카롱',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'스트로베리 초콜릿 생크림',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'씨 프렌즈 캔디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'아몬드 토피넛 캔디',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'아이스크림 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'에그 베이컨 브리오슈 밀박스',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'에그 브레드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'연어 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'옛날 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'오레오 치즈 큐브',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'와사비 크래미 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'왕 새우 튀김 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'치즈 갈릭 브레드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'치킨 B.L.T 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'치킨 텐더 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'치킨 텐더 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'카라멜 와플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'코코넛 청크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'크랜베리 치킨 치즈 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'크랜베리 닭가슴살 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'크루아상',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'크로플',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'크리미 토마토',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'크림 치즈 브리오슈 보스톡',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'클라우드 치즈케이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'클래식 스콘',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'트러플 머쉬룸 수프',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'트로피칼 치킨 샐러드',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'트리플 미니 스콘',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'트리플 치즈 크로크무슈',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'파이유',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'프렌치토스트',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'프로틴 블랙푸드 쉐이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'플레인 베이글',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'플레인 치즈 큐브',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'피넛 쑥떡 스콘',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'피칸 브라우니',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'하트 파이',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'한라봉 가득 핸디 젤리',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'함박 스테이크',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'핫 불닭 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'해시 베이컨 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'햄 바질 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'햄 에그 샌드위치',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'허니 갈릭 치아바타',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'허니 갈릭 피자',default);
insert into hashtag_classification values (hashtag_id_seq.nextval, hashtag_dmenu_id_seq.nextval,'허니 버터 브레드',default);

commit;
